##############################################################################
# Template sensors to report Kodi media player activity by @squirtbrnr
#
# Requires the Kodi component is loaded with a device named: media_player.kodi
#
# This is used to create the necessary template sensors used in the file
# packages/plate01/hasp_plate01_p8_media.yaml
# Comment out the template sensor created in that file to use this config with
# the Kodi media player.

sensor:
  - platform: template
    sensors:
      media_player_title:
        friendly_name: Title
        value_template: >-
          {%- if states.media_player.kodi.state == "playing" or "paused" -%}
            {%- if states.media_player.kodi.attributes.media_content_type == "tvshow" -%}
              S{%- if states.media_player.kodi.attributes.media_season < 10 -%}0{%- endif -%}{{ states.media_player.kodi.attributes.media_season }}E{%- if states.media_player.kodi.attributes.media_episode < 10 -%}0{%- endif -%}{{ states.media_player.kodi.attributes.media_episode }} - {{ states.media_player.kodi.attributes.media_title }}
            {%- else -%}
              {{ states.media_player.kodi.attributes.media_title }}
            {%- endif -%}
          {%- else -%}
            
          {%- endif -%}
        icon_template: mdi:television-classic
      media_player_artist:
        friendly_name: Series
        value_template: >-
          {%- if states.media_player.kodi.state == "playing" or "paused" and states.media_player.kodi.attributes.media_content_type == "tvshow" -%}
            {{ states.media_player.kodi.attributes.media_series_title }}
          {%- else -%}
            
          {%- endif -%}
        icon_template: mdi:television-classic
      media_player_volume:
        friendly_name: Volume
        value_template: >-
          {%- if states.media_player.kodi.attributes.volume_level -%}
            {{ states.media_player.kodi.attributes.volume_level * 100}}
          {%- else -%}
            0
          {%- endif -%}
        unit_of_measurement: '%'
        icon_template: >-
          {%- if 66 < states.media_player.kodi.attributes.volume_level * 100 <= 100 -%}
            mdi:volume-high
          {%- elif 33 < states.media_player.kodi.attributes.volume_level * 100 <= 66 -%}
            mdi:volume-medium
          {%- elif 0 < states.media_player.kodi.attributes.volume_level * 100 <= 33 -%}
            mdi:volume-low
          {%- elif states.media_player.kodi.attributes.volume_level * 100 == 0 -%}
            mdi:volume-off
          {%- else -%}
            mdi:volume-mute
          {%- endif -%}